### ISSUE TITLE
somecompany ревью

### ISSUE THREAD

**Issue by nikvst** [HeavyOranJS/fogstream-assignment#1]
owner-edit: убрано название компании, слишком легко гуглится и руинит тест

1. https://github.com/HeavyOranJS/somecompany-test-assignment/blob/master/assignment/views.py#L50
Может упасть если username пустой. Есть смысл обернуть в try...except User.DoesNotExist.

2. https://github.com/HeavyOranJS/somecompany-test-assignment/blob/master/assignment/models.py
К моделям и к полям моделей следует указывать verbose_name

3. https://github.com/HeavyOranJS/somecompany-test-assignment/blob/master/best_data_base.png
А что такое family_name у employee?

4. https://github.com/HeavyOranJS/somecompany-test-assignment/blob/master/somecompany-testTest/settings.py#L44
ALLOWED_HOST тоже нужно задавать в json файле

5. https://github.com/HeavyOranJS/somecompany-test-assignment/blob/overtime/assignment/forms.py#L81
тут тоже не хватает обработки исключений. Для сетевых запросов советую https://github.com/not-kennethreitz/requests (ты только глянь на количество звезочек!)

6. https://github.com/HeavyOranJS/somecompany-test-assignment/blob/master/somecompany-testTest/dummy.config.json#L2
=)

В целом неплохо, молодец.

**Comment by HeavyOranJS** [comment]
edit: убрано название компании, слишком легко гуглится и руинит тест

Спасибо за ревью! Прикрепление коммитов работает агрессивнее, чем я думал, прошу прощения.
Перенес все готовые изменения в мастер, поэтому ссылки туда. В overtime остались эксперименты с докером.

1. [Исправил](https://github.com/HeavyOranJS/somecompany-test-assignment/commit/2aa22f71061b00ec86ce768b7bea9e2005f6c994#diff-594ae1773a831b39f9896bb97189b9a6R52) и добавил [тесты](https://github.com/HeavyOranJS/somecompany-test-assignment/commit/2aa22f71061b00ec86ce768b7bea9e2005f6c994#diff-f0ebb526f76a7eab1efd3a6d181f90c2R81)

2. Не увидел разницу между синтаксисом типа 
`time = models.DateTimeField("Date the message was sent")`
и явным verbose_name, может быть надо было прописать явно что за параметр отправляется. [Документация](https://docs.djangoproject.com/en/2.2/topics/db/models/#verbose-field-names) и [скриншот](https://i.imgur.com/OSfkzv5.png) логов в моей панели администратора. К модели [добавил](https://github.com/HeavyOranJS/somecompany-test-assignment/commit/c83ad400496d7d975693b3987e37dd82eea77757#diff-81df11e0f3329f4fdc231f2214daf66dR20).

3. А это я опозорился с английским. Всю жизнь думал, что отчество это surname, а на самом деле фамилия, так же как и family name. Отчество оказалось patronymic, буду знать

4. [Убрал ](https://github.com/HeavyOranJS/somecompany-test-assignment/commit/0fe1e6ce17cfa58ce1da38cae399b9cad039e9c7#diff-b86c1eae0393062011f5e10b20368194R44) в config.json

5. Звездочек много, очень понравилось. Исправил на [одну строку](https://github.com/HeavyOranJS/somecompany-test-assignment/commit/d435939aa43b8f885d04ab3a87d201afabb1084c#diff-bd80fafa7257940c5e3ecfbf76e1cd83R86) с использованием requests. [Исключение](https://github.com/HeavyOranJS/somecompany-test-assignment/commit/85ca1f7ae4015fb1524bff6f7990f9713478e274#diff-bd80fafa7257940c5e3ecfbf76e1cd83R86) добавил, заодно исправил оплошность с генератором, и добавил [тест](https://github.com/HeavyOranJS/somecompany-test-assignment/commit/85ca1f7ae4015fb1524bff6f7990f9713478e274#diff-f0ebb526f76a7eab1efd3a6d181f90c2R203).

Эксперименты с докером не привожу, потому что еще не понял как работать с секретами, а без них приходится Dockerfile писать приватные данные бд. Пока что в settings.py прописаны стандартные данные постгреса, так работает.
